config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  

 get '/posts/new', to: 'posts#new', as: :new_post

  resources :users do
    resources :posts
  end

  resources :posts do
    resources :comments
    resources :likes
  end

  root to: "home#index"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, presence: true,
                                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  def update_posts_counter(id)
    counts = Post.where(user_id: id).count
    user = User.find(id)
    user.update(posts_counter: counts)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_user, only: [:create]

  def find_user
    @user = User.find(params[:user_id] || current_user.id)
  end

  def index
    @posts = find_user.posts.includes(:comments)
  end

  def show
    @post = find_user.posts.includes(comments: [:user]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    @post = @user.posts.new(
      title: post_params[:title],
      text: post_params[:text],
      user_id: post_params[:user_id],
      comments_counter: 0,
      likes_counter: 0
    )

    if @post.save
      @post.update_posts_counter(params[:user_id])
      redirect_to user_path(current_user.id)
      flash[:success] = 'Post saved successfully'
    else
      render :new
      flash.now[:error] = 'Post not saved'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      @post.update_posts_counter(@post.user_id)
      redirect_to users_path, status: 303
      flash[:success] = 'Post deleted successfully'
    else
      redirect_to users_path, status: 303
      flash.now[:error] = 'Post not deleted'
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :text)
  end
end

app/views/posts/index.html.erb
<div class="posts-home">
  <div class='flex inline'>
    <img src="<%= @user.photo %>" alt="User image" class="details-box"/>
    <div class="details-box width-75">
      <h2><%= @user.name %></h2>
      <p class="right">Number of Posts: <%= @user.posts_counter || 0 %></p>
    </div>
   
  </div>
</div>

<% @posts.each.with_index(1) do |post, index| %>
<div class="details-box posts">
  <h3> Post # <%= index %> <a href="<%= user_post_path(post.user.id, post.id)%>"><%= post.title %></a></h3>
  <p><%= post.text %></p>
  <p class="small-text right">
    Comments: <%= post.comments_counter || 0 %> ,
    Likes: <%= post.likes_counter || 0%>,
    <% if can? :destroy, post%>
      <%= button_to "Delete Posts", post_path(post.id), method: :delete %>
    <% end %>
  </p>
</div>
<div class="details-box comments">
<h4>Comments:</h4>
  <%if Comment.all.where(post_id: post.id).length != 0%>
    <%Comment.all.where(post_id: post.id).each do |comment| %>
      <%user = User.all.find(comment.user_id)%>
      <p> <%= user.name %>: <%= comment.text%></p>
    <%end%>
  <%end%>  
</div>
<br>

<% end %>

<div>
   <button class="center">Page</button>
</div>

app/views/posts/new.html.erb
<h1>Enjoy posts from our authors</h1>

<%= form_with model: @post, url: "/users/#{current_user.id}/posts" do |f| %>

<div>
    <%= f.hidden_field :user_id, value: current_user.id %>
</div>
<div class="details-box">
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :Message  %>
      <%= f.text_area :text %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  </div>

<% end%>

app/views/posts/show.html.erb
<div class="details-box posts">
  <h3> Post by: <%= @user.name %></h3>
  <h4>Title: <%= @post.title%></h4>
  <p><%= @post.text %></p>
  <p class="small-text right">
    Comments: <%= @post.comments_counter || 0 %> ,
    Likes: <%= @post.likes_counter || 0%>
  </p>
</div>
<div>
  <%= form_with url: "/posts/#{@post.id}/comments", scope: :comment do |form| %>
  <div >
    <%= form.label :text %>
    <%= form.text_area :text, required: true %>
  </div>
  <%= form.submit "Add Comment"%>
  <% end %>

  <%= form_with  url: "/posts/#{@post.id}/likes", scope: :like do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "Like "%>
  <% end %>
  <% if can? :destroy, @post%>
    <%= button_to "Delete Posts", post_path(@post.id), method: :delete %>
  <% end %>
</div>
<div class="details-box comments">
<h4>Comments:</h4>
  <%if Comment.all.where(post_id: @post.id).length != 0%>
    <%Comment.all.where(post_id: @post.id).each do |comment| %>
      <%user = User.all.find(comment.user_id)%>
      <p> <%= user.name %>: <%= comment.text%></p>


      <% if can? :destroy, comment %>
        <%= button_to "Delete Comment", post_comment_path(@post.id, comment.id), method: :delete %>
      <% end %>

      
    <%end%>
  <%end%>
</div>

<br>